apiVersion: v1
kind: Secret
metadata:
  name: template-service-secret
  namespace: template-service
type: Opaque
data:
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # your-secret-key-change-in-production

---
apiVersion: v1
kind: Secret
metadata:
  name: template-service-db-secret
  namespace: template-service
type: Opaque
data:
  POSTGRES_DB: dGVtcGxhdGVfc2VydmljZQ==  # template_service
  POSTGRES_USER: cG9zdGdyZXM=            # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=        # password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-service-config
  namespace: template-service
data:
  PORT: "8082"
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  DATABASE_URL: "postgres://postgres:password@template-service-postgres.template-service.svc.cluster.local:5432/template_service?sslmode=disable"
  AUTO_MIGRATE: "true"
  SEED_DATA: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-service-db-config
  namespace: template-service
data:
  POSTGRES_DB: template_service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service-postgres
  namespace: template-service
  labels:
    app: template-service-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-service-postgres
  template:
    metadata:
      labels:
        app: template-service-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: template-service-db-config
        - secretRef:
            name: template-service-db-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: template-service-postgres-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: template-service-postgres-pvc
  namespace: template-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: template-service-postgres
  namespace: template-service
  labels:
    app: template-service-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: template-service-postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service
  namespace: template-service
  labels:
    app: template-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: template-service
  template:
    metadata:
      labels:
        app: template-service
    spec:
      containers:
      - name: template-service
        image: alexinteam/report-system-template-service:latest
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: template-service-config
        - secretRef:
            name: template-service-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: template-service-service
  namespace: template-service
  labels:
    app: template-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: template-service
