apiVersion: v1
kind: Secret
metadata:
  name: report-service-secret
  namespace: report-service
type: Opaque
data:
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # your-secret-key-change-in-production

---
apiVersion: v1
kind: Secret
metadata:
  name: report-service-db-secret
  namespace: report-service
type: Opaque
data:
  POSTGRES_DB: cmVwb3J0X3NlcnZpY2U=      # report_service
  POSTGRES_USER: cG9zdGdyZXM=            # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=        # password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: report-service-config
  namespace: report-service
data:
  PORT: "8083"
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  DATABASE_URL: "postgres://postgres:password@report-service-postgres.report-service.svc.cluster.local:5432/report_service?sslmode=disable"
  RABBITMQ_URL: "amqp://admin:admin@rabbitmq.system.svc.cluster.local:5672/"
  AUTO_MIGRATE: "true"
  SEED_DATA: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: report-service-db-config
  namespace: report-service
data:
  POSTGRES_DB: report_service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service-postgres
  namespace: report-service
  labels:
    app: report-service-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service-postgres
  template:
    metadata:
      labels:
        app: report-service-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: report-service-db-config
        - secretRef:
            name: report-service-db-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: report-service-postgres-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: report-service-postgres-pvc
  namespace: report-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: report-service-postgres
  namespace: report-service
  labels:
    app: report-service-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: report-service-postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: report-service
  labels:
    app: report-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: alexinteam/report-system-report-service:latest
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: report-service-config
        - secretRef:
            name: report-service-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: report-service-service
  namespace: report-service
  labels:
    app: report-service
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: report-service
